### ISSUE TITLE
Can't use `next-available` hardware reservation in the metal_device module

### ISSUE THREAD

**Issue by ctreatma** [equinix/ansible-collection-equinix#224]
##### SUMMARY

According to the collection docs, [users can specify `next-available` as the `hardware-reservation-id`](https://galaxy.ansible.com/ui/repo/published/equinix/cloud/content/module/metal_device/#parameters) to select an available reservation without having to specify a particular reservation's UUID.

In practice, this results in a 404 error.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`metal_device`

##### ANSIBLE VERSION

```paste below
equinix.cloud v0.10.0
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
   - name: "Create a device using reserved hardware"
     equinix.cloud.metal_device:
         project_id: "my-project-uuid"
         state: "present"
         hostname: "reservation_test"
         operating_system: "ubuntu_22_04"
         plan: "m3.small.x86"
         metro: "sv"
         hardware_reservation_id: "next-available"
```

##### EXPECTED RESULTS

Based on the Ansible collection docs and the underlying Metal API feature, I expect the playbook above to provision a Metal device on an unused hardware reservation in my project.

##### ACTUAL RESULTS

The playbook fails with the below error output

```paste below
Error in metal_device: (404)
Reason: Not Found
```
