### ISSUE TITLE
VRF reports changes even though nothing changed

### ISSUE THREAD

**Issue by ctreatma** [equinix/ansible-collection-equinix#236]
##### SUMMARY

When a VRF is configured with multiple IP ranges, the `metal_vrf` module will constantly report changes if the IP ranges are specified in a different order in Ansible than the order in which they come back from the API.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

The task below will report changes every time that it is run because the task config lists "192.168.0.0/25" first, but the API response lists "169.254.0.0/29" first.

```yaml
    - name: create a VRF
      equinix.cloud.metal_vrf:
        name: example-vrf
        metro: "sv"
        local_asn: 65000
        ip_ranges:
          - "192.168.0.0/25"
          - "169.254.0.0/29"
        project_id: "{{ project.id }}"
```

##### ACTUAL RESULTS

```paste below

```
