### ISSUE TITLE
metal_port

### ISSUE THREAD

**Issue by t0mk** [equinix/ansible-collection-equinix#61]
Create module for metal_port.

Analogical to resource equinix_metal_port in terraform-provider-equinix:

- https://registry.terraform.io/providers/equinix/equinix/latest/docs/resources/equinix_metal_port
- https://github.com/equinix/terraform-provider-equinix/tree/master/equinix/resource_metal_port.go

Module should
- be in `plugins/modules/metal_port.py`
- follow [development conventions](https://docs.ansible.com/ansible/devel/dev_guide/developing_modules_best_practices.html)
- be [idempotent](https://docs.ansible.com/ansible/latest/reference_appendices/glossary.html#term-Idempotency>)
- support `check_mode` if it's an `_info` module
- have doc fields for (ansible-specdoc)[https://github.com/linode/ansible-specdoc] (see [metal_project.py](https://github.com/equinix-labs/ansible-collection-equinix/blob/main/plugins/modules/metal_project.py) for an example
  - module_spec
  - specdoc_example
  - result_sample
  - SPECDOC_METAL
  - (DOCUMENATION, EXAMPLES and RETURN will be generated by `make docs`)
- have an integration test in `tests/integration/targets/metal_port/tasks/main.yml`
- (semi-optional) pass sanity test: 
  `$ cd .ansible/collections/ansible_collections/equinix/cloud`
  `$ ansible-test sanity -v --docker --python 3.10 metal_port.py`

See the newest added module to get an idea how to do implement this.

**Comment by displague** [comment]
This is a Terraform-ism that we potentially don't need if the ports are made to be configurable in the Metal Device.

**Comment by ctreatma** [comment]
> This is a Terraform-ism that we potentially don't need if the ports are made to be configurable in the Metal Device.

The metal_device module doesn't seem to support port configuration.  Should we add port configuration support to metal_device or add a separate metal_port module?  In its current state, the Ansible collection cannot be used to put a device in L2 mode.

**Comment by displague** [comment]
After thinking more about this, the /ports* APIs are a feature all their own and they have (potential) use beyond devices.

**Comment by displague** [comment]
Looking at the TF provider, I think the module would look like:
```yaml
  tasks:
    - equinix.cloud.metal_port:
        port_id: "3b516842-c8b1-485e-9f76-c891bd804c5e" # required lookup
        bonded: true/false
        layer2: true/false
        vxlan_ids: [1234, 5678]
        vlans_ids: [uuid, uuid]
        reset_on_delete: true/false # ansible behavior
        # read-only
        name: bond0
        network_type: NetworkBondPort
        type: ...
        mac: ...
        bond_id: ...
        bond_name: ...
        disbond_supported: ...
```

Inventory would return the same based on port_id.

There may be other considerations from a purely API spec view.
